language: python
python: "3.6"
services: mysql
before-install: cd server
install: pip install -r server/requirements.txt
before_script:
  - mysql -u root -e "SET GLOBAL max_connections = 1000;"
  - mysql -u root < sql/setup.sql
  - mysql -u ygoons_test --password=Public1! < sql/reset.sql
script: "yapf -d -r . && make test"
